config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path, re_path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
from drf_spectacular.views import (
    SpectacularJSONAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)

from print_nanny_webapp.surveys.views import RemoteAccessSurvey1Create
from print_nanny_webapp.users.views import ThanksView
from print_nanny_webapp.subscriptions.views import FoundingMemberSignupView

# Webapp urls
urlpatterns = [
    re_path(r"^health/", include("health_check.urls"), name="health"),
    path("", TemplateView.as_view(template_name="landing/landing.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    path("request-invite/", RemoteAccessSurvey1Create.as_view(), name="request-invite"),
    path("invite/", RemoteAccessSurvey1Create.as_view(), name="invite"),
    path("waitlist/", RemoteAccessSurvey1Create.as_view(), name="waitlist"),
    path("thanks/", ThanksView.as_view(), name="thanks"),
    # Django Admin, use {% url 'admin:index' %}
    # django-loginas urls must be defined before admin.site.urls
    path(settings.ADMIN_URL, include("loginas.urls")),
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("print_nanny_webapp.users.urls", namespace="users")),
    # path("remote-control/", include("print_nanny_webapp.remote_control.urls", namespace="remote-control")),
    path("accounts/", include("allauth.urls")),
    path("signin/", RedirectView.as_view(url="/accounts/login/", permanent=True)),
    path(
        "dashboard/",
        include("print_nanny_webapp.dashboard.urls", namespace="dashboard"),
    ),
    path("alerts/", include("print_nanny_webapp.alerts.urls", "alerts")),
    re_path(r"^invitations/", include("invitations.urls", namespace="invitations")),
    path(
        "devices/",
        include("print_nanny_webapp.devices.urls", namespace="devices"),
    ),
    path("surveys/", include("print_nanny_webapp.surveys.urls", namespace="urls")),
    path(
        "octoprint/",
        include("print_nanny_webapp.octoprint.urls", namespace="octoprint"),
    ),
    path("", include("qr_code.urls", namespace="qr_code")),
    path("trial", FoundingMemberSignupView.as_view(), name="trial"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += (
    path(
        "subscriptions/",
        include("print_nanny_webapp.subscriptions.urls", "subscriptions"),
    ),
)
urlpatterns += (path("stripe/", include("djstripe.urls", namespace="djstripe")),)


if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# API URLS

# https://drf-spectacular.readthedocs.io/en/latest/blueprints.html
# do not remove the following line!
import print_nanny_webapp.drfpasswordless.schema

urlpatterns += [
    # API base urls
    path("api/", include("config.api_router")),
    # OpenAPI Schema
    path("api/schema/", SpectacularJSONAPIView.as_view(), name="schema"),
    # OpenAPI UIs
    path(
        "api/schema/swagger-ui/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
    path(
        "api/schema/redoc/",
        SpectacularRedocView.as_view(url_name="schema"),
        name="redoc",
    ),
    path("", include("django_prometheus.urls")),
    path("anymail/", include("anymail.urls")),
    # https://github.com/aaronn/django-rest-framework-passwordless
    path("", include("drfpasswordless.urls")),
]


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

print_nanny_webapp/alerts/urls.py
from django.urls import path, include, re_path


from .views import AlertSettingsView, AlertListView

app_name = "alerts"

urlpatterns = [
    path("settings", AlertSettingsView.as_view(), name="settings"),
    path("", AlertListView.as_view(), name="list"),
    re_path("^(\d+)/$", AlertListView.as_view(), name="list"),
]

print_nanny_webapp/pages/urls.py
from django.urls import path

from .views import (
    custom_pages_faq_view,
    custom_pages_invoice_view,
    custom_pages_maintenance_view,
    custom_pages_preloader_view,
    custom_pages_pricing_view,
    custom_pages_profile2_view,
    custom_pages_profile_view,
    custom_pages_starter_view,
    custom_pages_time_line_view,
    custom_pages_login_2_view,
    custom_pages_register_2_view,
    custom_pages_404_alt_view,
    custom_pages_404_view,
    custom_pages_500_view,
    custom_pages_confirm_mail_2_view,
    custom_pages_confirm_mail_view,
    custom_pages_recoverpw_2_view,
    custom_pages_logout_2_view,
    custom_pages_logout_view,
    custom_pages_lock_screen_2_view,
    custom_pages_lock_screen_view,
    custom_landing_landing_view,
)

app_name = "pages"
urlpatterns = [
    # pages
    path("faq", view=custom_pages_faq_view, name="faq"),
    path("invoice", view=custom_pages_invoice_view, name="invoice"),
    path("maintenance", view=custom_pages_maintenance_view, name="maintenance"),
    path("preloader", view=custom_pages_preloader_view, name="preloader"),
    path("pricing", view=custom_pages_pricing_view, name="pricing"),
    path("profile2", view=custom_pages_profile2_view, name="profile-2"),
    path("profile", view=custom_pages_profile_view, name="profile"),
    path("starter", view=custom_pages_starter_view, name="starter"),
    path("time-line", view=custom_pages_time_line_view, name="timeline"),
    path("login-2", view=custom_pages_login_2_view, name="login-2"),
    path("register-2", view=custom_pages_register_2_view, name="register-2"),
    path("404_alt", view=custom_pages_404_alt_view, name="404-alt"),
    path("404", view=custom_pages_404_view, name="404"),
    path("500", view=custom_pages_500_view, name="500"),
    path(
        "confirm-mail-2", view=custom_pages_confirm_mail_2_view, name="confirm-mail-2"
    ),
    path("confirm-mail", view=custom_pages_confirm_mail_view, name="confirm-mail"),
    path("recoverpw-2", view=custom_pages_recoverpw_2_view, name="recoverpw-2"),
    path("logout-2", view=custom_pages_logout_2_view, name="logout-2"),
    path("logout", view=custom_pages_logout_view, name="logout"),
    path("lock-screen-2", view=custom_pages_lock_screen_2_view, name="lock-screen-2"),
    path("lock-screen", view=custom_pages_lock_screen_view, name="lock-screen"),
    # landing
    path("landing", view=custom_landing_landing_view, name="landing"),
]

print_nanny_webapp/users/urls.py
from django.urls import path
import base64

from print_nanny_webapp.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("settings/", view=user_detail_view, name="detail"),
]

clients/python/printnanny_api_client/models/user.py
# coding: utf-8

"""
    printnanny-api-client

    Official API client library forprintnanny.ai print-nanny.com  # noqa: E501

    The version of the OpenAPI document: 0.0.0
    Contact: leigh@printnanny.ai
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from printnanny_api_client.configuration import Configuration


class User(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'email': 'str',
        'id': 'int'
    }

    attribute_map = {
        'email': 'email',
        'id': 'id'
    }

    def __init__(self, email=None, id=None, local_vars_configuration=None):  # noqa: E501
        """User - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._email = None
        self._id = None
        self.discriminator = None

        self.email = email
        self.id = id

    @property
    def email(self):
        """Gets the email of this User.  # noqa: E501


        :return: The email of this User.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this User.


        :param email: The email of this User.  # noqa: E501
        :type email: str
        """
        if self.local_vars_configuration.client_side_validation and email is None:  # noqa: E501
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                email is not None and len(email) > 254):
            raise ValueError("Invalid value for `email`, length must be less than or equal to `254`")  # noqa: E501

        self._email = email

    @property
    def id(self):
        """Gets the id of this User.  # noqa: E501


        :return: The id of this User.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this User.


        :param id: The id of this User.  # noqa: E501
        :type id: int
        """
        if self.local_vars_configuration.client_side_validation and id is None:  # noqa: E501
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, User):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, User):
            return True

        return self.to_dict() != other.to_dict()

print_nanny_webapp/dashboard/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.postgres.fields import ArrayField

User = get_user_model()


class AppCategoryChoices(models.TextChoices):
    NOTIFICATIONS = "Notifcations", "Notifications"
    ECOMMERCE = "Ecommerce", "Ecommerce"
    AUTOMATION = "Automation", "Automation"


class AppCard(models.Model):

    """
    Dummy app integration card used to measure interest from users via "notification" feature
    """

    static_image = models.CharField(max_length=255, null=True)
    name = models.CharField(max_length=255)
    service_url = models.CharField(max_length=255)
    category = models.CharField(max_length=255, choices=AppCategoryChoices.choices)


class AppNotification(models.Model):
    created_dt = models.DateTimeField(auto_now_add=True)
    app = models.ForeignKey(AppCard, on_delete=models.CASCADE, db_index=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, db_index=True)

print_nanny_webapp/alerts/forms.py
from django.apps import apps
from django.forms import ModelForm, Form


AlertSettings = apps.get_model("alerts", "AlertSettings")


class AlertTestForm(Form):
    pass


class AlertSettingsForm(ModelForm):
    class Meta:
        model = AlertSettings
        fields = ("event_types", "print_progress_percent")


class AlertMethodSettingsForm(ModelForm):
    class Meta:
        model = AlertSettings
        fields = ("alert_methods", "discord_webhook")

print_nanny_webapp/dashboard/forms.py
import logging
from django import forms
from django.apps import apps

from crispy_forms.helper import FormHelper

logger = logging.getLogger(__name__)


class PushNotificationsForm(forms.Form):
    email = forms.BooleanField(label="Receive email notifications")
    discord = forms.BooleanField(label="Receive discord notifications")
    geeks_3d = forms.BooleanField(
        label="Receive push notifications from 3D Geeks mobile app"
    )


class RemoveDeviceForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = "post"


class TimelapseUploadForm(forms.Form):

    video_file = forms.FileField(label="Select a video file (.mp4)", required=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = "post"


class TimelapseCancelForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = "post"


class LicenseGenerateForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = "post"


class FeedbackForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = "post"


class AppNotificationForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = "post"


class RemoteControlCommandForm(forms.Form):

    command = forms.ChoiceField()

    def __init__(self, *args, **kwargs):

        # django metaclass magic to construct fields

        command_choices = kwargs.pop("command_choices")
        print(f"received command choices {command_choices}")
        super().__init__(*args, **kwargs)
        self.fields["command"].choices = [(x.value, x.label) for x in command_choices]

print_nanny_webapp/devices/forms.py
# add device forms here

print_nanny_webapp/octoprint/forms.py
from django import forms
from .models import OctoPrintSettings


class OctoPrintSettingsForm(forms.ModelForm):
    class Meta:
        model = OctoPrintSettings
        exclude = ("user",)

print_nanny_webapp/partners/forms.py
from django import forms


class RevokeGeeksTokenForm(forms.Form):
    pass

print_nanny_webapp/subscriptions/forms.py
from django import forms
from .models import ReferralCode, ReferralInvite


class PromoCodeForm(forms.Form):
    code = forms.CharField()


class StripeCheckoutForm(forms.Form):
    """
    Create a Stripe Checkout Session & then redirect to checkout page
    https://stripe.com/docs/payments/accept-a-payment?platform=web&ui=checkout
    """

    pass


class ReferralCodeCreateForm(forms.ModelForm):
    class Meta:
        model = ReferralCode
        fields = ("code",)


class ReferralInviteCreateForm(forms.ModelForm):
    class Meta:
        model = ReferralInvite
        fields = ("email",)

print_nanny_webapp/templates/users/inviterequest_form.html
{% extends "account/base.html" %}

{% load static i18n %}

{% block head_title %}{% trans "Register" %}{% endblock head_title %}
{% load crispy_forms_tags %}

{% block body_extra %}
class="loading authentication-bg" data-layout-config='{"leftSideBarTheme":"dark","layoutBoxed":false,
"leftSidebarCondensed":false, "leftSidebarScrollable":false,"darkMode":false, "showRightSidebarOnStart": true}'
{% endblock body_extra %}

{% block content %}

<div class="account-pages mt-5 mb-5">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card">
                    <!-- Logo-->
                    <div class="card-header pt-4 pb-4 text-center bg-primary">
                        <a href="{% url 'dashboard:home' %}">
                            <span><img src="{% static 'images/logo-text-white.svg' %}" alt="" height="18"></span>
                        </a>
                    </div>

                    <div class="card-body p-4">

                        <div class="text-center w-75 m-auto">
                            <h4 class="text-dark-50 text-center mt-0 font-weight-bold">{% trans "Request Beta Invite" %}
                            </h4>
                            <p class="mb-4">Hey, thanks for your interest in testing PrintNanny!</p>

                            <p>Please fill out the form below to request a Beta invitation.</p>
                        </div>

                        <form class="signup" id="signup_form" method="post" action="{% url 'request-invite' %}">
                            {% csrf_token %}
                            {{ form|crispy }}
                            {% if redirect_field_value %}
                            <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
                            {% endif %}
                            <button class="btn btn-primary" type="submit">{% trans "Submit" %} &raquo;</button>
                        </form>
                    </div> <!-- end card-body -->
                </div>
                <!-- end card -->


            </div> <!-- end col -->
        </div>
        <!-- end row -->
    </div>
    <!-- end container -->
</div>
<!-- end page -->

{% endblock content %}

print_nanny_webapp/templates/users/thanks.html
{% extends "account/base.html" %}

{% load static i18n %}

{% block head_title %}{% trans "Register" %}{% endblock head_title %}
{% load crispy_forms_tags %}

{% block body_extra %}
class="loading authentication-bg" data-layout-config='{"leftSideBarTheme":"dark","layoutBoxed":false,
"leftSidebarCondensed":false, "leftSidebarScrollable":false,"darkMode":false, "showRightSidebarOnStart": true}'
{% endblock body_extra %}

{% block content %}

<div class="account-pages mt-5 mb-5">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card">
                    <div class="card-body">
                        <h1 class="display-4">Thank you!</h1>


                        <p>You'll get an email when space becomes available in the Beta program. I'm excited to hear
                            what you think! If you have questions in the meantime, join Discord or send me an email.
                            - Leigh
                        </p>
                        <img class="col-sm-3 col-lg-2 img-fluid" src="{% static 'images/love.svg' %}">

                        <a target="_blank" href="{{DISCORD_URL}}">
                            <button target="_blank" href="{{DISCORD_URL}}" type="button"
                                class="discord btn btn-primary btn-sm mt-2 ml-1"><i
                                    class="mdi mdi-discord mr-1"></i>Join Discord</button>

                        </a>
                        <a target="_blank" href="mailto:leigh@printnanny.ai">
                            <button type="button" id="support-email" class="btn btn-success btn-sm mt-2"><i
                                    class="mdi mdi-email-outline mr-1"></i> Email</button>

                        </a>
                        <a target="_blank" id="twitter"
                            href="https://twitter.com/intent/tweet?text=Hey%20@grepLeigh%20-%20question%20about%20PrintNanny">
                            <button type="button" class="btn btn-info btn-sm mt-2 ml-1"><i
                                    class="mdi mdi-twitter mr-1"></i>Tweet</button>

                        </a>

                    </div>

                </div>
            </div>


            <!-- end col -->
        </div>
        <!-- end row -->
    </div>
    <!-- end container -->
</div>
<!-- end page -->

{% endblock content %}

{% block extra_javascript %}
<script>
    gtag('event', 'beta_invite_request')
</script>
{% endblock %}

print_nanny_webapp/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

print_nanny_webapp/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
{% endblock %}