config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path, re_path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
from drf_spectacular.views import (
    SpectacularJSONAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)

from print_nanny_webapp.surveys.views import RemoteAccessSurvey1Create
from print_nanny_webapp.users.views import ThanksView
from print_nanny_webapp.subscriptions.views import FoundingMemberSignupView

# Webapp urls
urlpatterns = [
    re_path(r"^health/", include("health_check.urls"), name="health"),
    path("", TemplateView.as_view(template_name="landing/landing.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    path("request-invite/", RemoteAccessSurvey1Create.as_view(), name="request-invite"),
    path("invite/", RemoteAccessSurvey1Create.as_view(), name="invite"),
    path("waitlist/", RemoteAccessSurvey1Create.as_view(), name="waitlist"),
    path("thanks/", ThanksView.as_view(), name="thanks"),
    # Django Admin, use {% url 'admin:index' %}
    # django-loginas urls must be defined before admin.site.urls
    path(settings.ADMIN_URL, include("loginas.urls")),
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("print_nanny_webapp.users.urls", namespace="users")),
    # path("remote-control/", include("print_nanny_webapp.remote_control.urls", namespace="remote-control")),
    path("accounts/", include("allauth.urls")),
    path("signin/", RedirectView.as_view(url="/accounts/login/", permanent=True)),
    path(
        "dashboard/",
        include("print_nanny_webapp.dashboard.urls", namespace="dashboard"),
    ),
    path("alerts/", include("print_nanny_webapp.alerts.urls", "alerts")),
    re_path(r"^invitations/", include("invitations.urls", namespace="invitations")),
    path(
        "devices/",
        include("print_nanny_webapp.devices.urls", namespace="devices"),
    ),
    path("surveys/", include("print_nanny_webapp.surveys.urls", namespace="urls")),
    path(
        "octoprint/",
        include("print_nanny_webapp.octoprint.urls", namespace="octoprint"),
    ),
    path("", include("qr_code.urls", namespace="qr_code")),
    path("trial", FoundingMemberSignupView.as_view(), name="trial"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += (
    path(
        "subscriptions/",
        include("print_nanny_webapp.subscriptions.urls", "subscriptions"),
    ),
)
urlpatterns += (path("stripe/", include("djstripe.urls", namespace="djstripe")),)


if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# API URLS

# https://drf-spectacular.readthedocs.io/en/latest/blueprints.html
# do not remove the following line!
import print_nanny_webapp.drfpasswordless.schema

urlpatterns += [
    # API base urls
    path("api/", include("config.api_router")),
    # OpenAPI Schema
    path("api/schema/", SpectacularJSONAPIView.as_view(), name="schema"),
    # OpenAPI UIs
    path(
        "api/schema/swagger-ui/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
    path(
        "api/schema/redoc/",
        SpectacularRedocView.as_view(url_name="schema"),
        name="redoc",
    ),
    path("", include("django_prometheus.urls")),
    path("anymail/", include("anymail.urls")),
    # https://github.com/aaronn/django-rest-framework-passwordless
    path("", include("drfpasswordless.urls")),
]


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

print_nanny_webapp/alerts/urls.py
from django.urls import path, include, re_path


from .views import AlertSettingsView, AlertListView

app_name = "alerts"

urlpatterns = [
    path("settings", AlertSettingsView.as_view(), name="settings"),
    path("", AlertListView.as_view(), name="list"),
    re_path("^(\d+)/$", AlertListView.as_view(), name="list"),
]

print_nanny_webapp/pages/urls.py
from django.urls import path

from .views import (
    custom_pages_faq_view,
    custom_pages_invoice_view,
    custom_pages_maintenance_view,
    custom_pages_preloader_view,
    custom_pages_pricing_view,
    custom_pages_profile2_view,
    custom_pages_profile_view,
    custom_pages_starter_view,
    custom_pages_time_line_view,
    custom_pages_login_2_view,
    custom_pages_register_2_view,
    custom_pages_404_alt_view,
    custom_pages_404_view,
    custom_pages_500_view,
    custom_pages_confirm_mail_2_view,
    custom_pages_confirm_mail_view,
    custom_pages_recoverpw_2_view,
    custom_pages_logout_2_view,
    custom_pages_logout_view,
    custom_pages_lock_screen_2_view,
    custom_pages_lock_screen_view,
    custom_landing_landing_view,
)

app_name = "pages"
urlpatterns = [
    # pages
    path("faq", view=custom_pages_faq_view, name="faq"),
    path("invoice", view=custom_pages_invoice_view, name="invoice"),
    path("maintenance", view=custom_pages_maintenance_view, name="maintenance"),
    path("preloader", view=custom_pages_preloader_view, name="preloader"),
    path("pricing", view=custom_pages_pricing_view, name="pricing"),
    path("profile2", view=custom_pages_profile2_view, name="profile-2"),
    path("profile", view=custom_pages_profile_view, name="profile"),
    path("starter", view=custom_pages_starter_view, name="starter"),
    path("time-line", view=custom_pages_time_line_view, name="timeline"),
    path("login-2", view=custom_pages_login_2_view, name="login-2"),
    path("register-2", view=custom_pages_register_2_view, name="register-2"),
    path("404_alt", view=custom_pages_404_alt_view, name="404-alt"),
    path("404", view=custom_pages_404_view, name="404"),
    path("500", view=custom_pages_500_view, name="500"),
    path(
        "confirm-mail-2", view=custom_pages_confirm_mail_2_view, name="confirm-mail-2"
    ),
    path("confirm-mail", view=custom_pages_confirm_mail_view, name="confirm-mail"),
    path("recoverpw-2", view=custom_pages_recoverpw_2_view, name="recoverpw-2"),
    path("logout-2", view=custom_pages_logout_2_view, name="logout-2"),
    path("logout", view=custom_pages_logout_view, name="logout"),
    path("lock-screen-2", view=custom_pages_lock_screen_2_view, name="lock-screen-2"),
    path("lock-screen", view=custom_pages_lock_screen_view, name="lock-screen"),
    # landing
    path("landing", view=custom_landing_landing_view, name="landing"),
]

print_nanny_webapp/subscriptions/urls.py
from django.urls import path

from print_nanny_webapp.subscriptions.views import (
    SubscriptionsListView,
    FoundingMemberSignupView,
    FoundingMemberCheckoutView,
    CheckoutSuccessView,
)

app_name = "subscriptions"

urlpatterns = [
    path(
        "signup",
        FoundingMemberSignupView.as_view(),
        name="signup",
    ),
    path(
        "trial",
        FoundingMemberCheckoutView.as_view(),
        name="trial",
    ),
    path(
        "checkout",
        FoundingMemberCheckoutView.as_view(),
        name="checkout",
    ),
    path(
        "checkout-success",
        CheckoutSuccessView.as_view(),
        name="checkout_success",
    ),
    path(
        "checkout-success/<slug:session_id>",
        CheckoutSuccessView.as_view(),
    ),
    path("", SubscriptionsListView.as_view(), name="list"),
]

print_nanny_webapp/surveys/urls.py
from django.urls import path, include
from .views import RemoteAccessSurvey1Success, RemoteAccessSurvey1Create

app_name = "surveys"

urlpatterns = [
    path("remote-access", RemoteAccessSurvey1Create.as_view(), name="remote-access"),
    path(
        "remote-access-thanks",
        RemoteAccessSurvey1Success.as_view(),
        name="remote-access-thanks",
    ),
]

print_nanny_webapp/users/urls.py
from django.urls import path
import base64

from print_nanny_webapp.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("settings/", view=user_detail_view, name="detail"),
]

print_nanny_webapp/dashboard/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.postgres.fields import ArrayField

User = get_user_model()


class AppCategoryChoices(models.TextChoices):
    NOTIFICATIONS = "Notifcations", "Notifications"
    ECOMMERCE = "Ecommerce", "Ecommerce"
    AUTOMATION = "Automation", "Automation"


class AppCard(models.Model):

    """
    Dummy app integration card used to measure interest from users via "notification" feature
    """

    static_image = models.CharField(max_length=255, null=True)
    name = models.CharField(max_length=255)
    service_url = models.CharField(max_length=255)
    category = models.CharField(max_length=255, choices=AppCategoryChoices.choices)


class AppNotification(models.Model):
    created_dt = models.DateTimeField(auto_now_add=True)
    app = models.ForeignKey(AppCard, on_delete=models.CASCADE, db_index=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, db_index=True)

print_nanny_webapp/alerts/forms.py
from django.apps import apps
from django.forms import ModelForm, Form


AlertSettings = apps.get_model("alerts", "AlertSettings")


class AlertTestForm(Form):
    pass


class AlertSettingsForm(ModelForm):
    class Meta:
        model = AlertSettings
        fields = ("event_types", "print_progress_percent")


class AlertMethodSettingsForm(ModelForm):
    class Meta:
        model = AlertSettings
        fields = ("alert_methods", "discord_webhook")

print_nanny_webapp/dashboard/forms.py
import logging
from django import forms
from django.apps import apps

from crispy_forms.helper import FormHelper

logger = logging.getLogger(__name__)


class PushNotificationsForm(forms.Form):
    email = forms.BooleanField(label="Receive email notifications")
    discord = forms.BooleanField(label="Receive discord notifications")
    geeks_3d = forms.BooleanField(
        label="Receive push notifications from 3D Geeks mobile app"
    )


class RemoveDeviceForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = "post"


class TimelapseUploadForm(forms.Form):

    video_file = forms.FileField(label="Select a video file (.mp4)", required=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = "post"


class TimelapseCancelForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = "post"


class LicenseGenerateForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = "post"


class FeedbackForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = "post"


class AppNotificationForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = "post"


class RemoteControlCommandForm(forms.Form):

    command = forms.ChoiceField()

    def __init__(self, *args, **kwargs):

        # django metaclass magic to construct fields

        command_choices = kwargs.pop("command_choices")
        print(f"received command choices {command_choices}")
        super().__init__(*args, **kwargs)
        self.fields["command"].choices = [(x.value, x.label) for x in command_choices]

print_nanny_webapp/devices/forms.py
# add device forms here

print_nanny_webapp/octoprint/forms.py
from django import forms
from .models import OctoPrintSettings


class OctoPrintSettingsForm(forms.ModelForm):
    class Meta:
        model = OctoPrintSettings
        exclude = ("user",)

print_nanny_webapp/partners/forms.py
from django import forms


class RevokeGeeksTokenForm(forms.Form):
    pass

print_nanny_webapp/subscriptions/forms.py
from django import forms
from .models import ReferralCode, ReferralInvite


class PromoCodeForm(forms.Form):
    code = forms.CharField()


class StripeCheckoutForm(forms.Form):
    """
    Create a Stripe Checkout Session & then redirect to checkout page
    https://stripe.com/docs/payments/accept-a-payment?platform=web&ui=checkout
    """

    pass


class ReferralCodeCreateForm(forms.ModelForm):
    class Meta:
        model = ReferralCode
        fields = ("code",)


class ReferralInviteCreateForm(forms.ModelForm):
    class Meta:
        model = ReferralInvite
        fields = ("email",)

print_nanny_webapp/surveys/forms.py
from typing import TYPE_CHECKING, Optional
from django.contrib.auth import get_user_model
from django.forms import (
    ModelForm,
    CharField,
    MultipleChoiceField,
    CheckboxSelectMultiple,
    BooleanField,
    Textarea,
)
from .choices import PrimaryOS, MobileOS, VPNExperience, UserScale, PrinterSoftware

from .models import RemoteAccessSurvey1

if TYPE_CHECKING:
    from print_nanny_webapp.users.models import User as UserType
User = get_user_model()


class RemoteAccessSurvey1Form(ModelForm):
    opt_in = BooleanField(
        required=True,
        label="I agree to receive email updates about Print Nanny development, patch notes, and upcoming features.",
    )
    primary_os = MultipleChoiceField(
        widget=CheckboxSelectMultiple,
        choices=PrimaryOS.choices,
        label="Which computer operating system do you use? Select all that apply.",
    )
    printer_models_other = CharField(
        label="If you checked Other, please add details here",
        required=False,
    )
    mobile_os = MultipleChoiceField(
        widget=CheckboxSelectMultiple,
        choices=MobileOS.choices,
        label="What kind of mobile phone do you use? Select all that apply",
    )
    vpn_experience = MultipleChoiceField(
        widget=CheckboxSelectMultiple,
        choices=VPNExperience.choices,
        label="Have you ever used a Virtual Private Network (VPN) or other remote access software? Select all that apply",
    )

    user_scale = MultipleChoiceField(
        widget=CheckboxSelectMultiple,
        choices=UserScale.choices,
        label="What are your goals for using Print Nanny OS + Network?",
    )

    user_scale_other = CharField(
        label="If you checked Other, please add details here",
        required=False,
    )

    printer_software = MultipleChoiceField(
        widget=CheckboxSelectMultiple,
        choices=PrinterSoftware.choices,
        label="Which printer management software do you use? Select all that apply",
    )

    printer_software_other = CharField(
        label="If you checked Other, please add details here or email leigh@printnanny.ai",
        required=False,
    )

    worst = CharField(
        label="If you could wave a magic wand and change ONE thing about 3D printing, what would that be?",
        widget=Textarea,
        help_text="Tell me what you hate most about 3D printing today",
        required=False,
    )

    class Meta:
        model = RemoteAccessSurvey1
        exclude = ["user", "user_agent"]

    def save(self, *args, **kwargs):
        request = kwargs.pop("request")
        if request is None:
            raise ValueError("request must be defined")
        # check to see if provided email matches user
        if request.user.is_anonymous:
            email = self.cleaned_data["email"]
            user = User.objects.filter(email=email).first()  # type: ignore
        else:
            user = request.user

        self.instance.user = user
        self.instance.user_agent = request.META
        return super(RemoteAccessSurvey1Form, self).save(*args, **kwargs)

print_nanny_webapp/templates/surveys/remote-access-form.html
{% extends "vertical_base.html" %}
{% load static %}
{% load crispy_forms_tags feature_flags %}

{% block content %}
<div class="account-pages mt-2 mb-5">
    <div class="container-fluid">
        <div class="card">
            <div class="card-body">

                <div class="card-header primary-gradient pt-4 pb-4 mb-4 text-center bg-primary text-white">
                    <h1 class="display-4">PrintNanny Network & File Manager</h1>
                    <h3>Manage your 3D printers from anywhere in the world
                    </h3>

                    {% if not user.is_paid_beta_tester %}
                    <a target="_blank" href="{% url 'subscriptions:checkout' %}"
                        class="mt-2 mb-2 btn btn-lg btn-light pull-left">Become a Founding Member</a>
                    <h3>{{ AVAILABLE_SUBSCRIPTIONS_COUNT }} spots left</h3>
                    {% endif %}

                </div>
                <div class="row">
                    <div class="col-12 ribbon-box col-md-6">
                        <div class="ribbon ribbon-primary float-left">
                            <h4 class="mb-2">PrintNanny Network & File Manager <span class="badge badge-light">Early
                                    Access</span></h4>
                        </div>
                        <div class="ribbon-content">
                            <h3>Answer the survey to join the waitlist.</strong>
                            </h3>
                            <form class="form" id="remote_access" method="post"
                                action="{% url 'surveys:remote-access' %}">
                                <div class="form-group">
                                    {% csrf_token %}
                                    {{ form|crispy }}
                                </div>
                                {% if redirect_field_value %}
                                <input type="hidden" name="{{ redirect_field_name }}"
                                    value="{{ redirect_field_value }}" />
                                {% endif %}
                                <button class="btn btn-primary" type="submit">Submit &raquo;</button>
                            </form>
                        </div>
                    </div>
                    {% include 'surveys/remote-access-sidebar.html'%}
                </div>
            </div>

        </div>
    </div>
</div>
{% endblock content %}

print_nanny_webapp/templates/surveys/remote-access-sidebar.html
{% load static %}

<div class="col-12 col-md-6 ribbon-box  bg-light">
    <div class="ribbon ribbon-primary float-left">
        <h4><strong>🎨 Mix and match any printer software.</strong></h4>
    </div>
    <div class="ribbon-content">
        <p><strong>Compatible with:
                <ul>
                    <li>OctoPrint</li>
                    <li>Moonraker API (Mainsail, Fluidd)</li>
                </ul>
            </strong>
        </p>
        <p>Email <a href="mailto:leigh@printnanny.ai">leigh@printnanny.ai</a> to request a new platform.</p>

        </p>
    </div>


    <div class="ribbon ribbon-primary float-left">
        <h4><strong>💜 One easy install with PrintNanny OS</strong></h4>
    </div>
    <div class="ribbon-content">
        <p>
            Designed by a <strong>Raspberry Pi devotee</strong>, for Raspberry Pi lovers worldwide.
            <img class="img-fluid" src="{% static 'images/rpi-imager-printnanny-os.png'%}" />
            <small class="text-muted text-center">Raspberry Pi is a trademark of Raspberry Pi Trading.</small>
        </p>
    </div>

    <div class="ribbon ribbon-primary float-left">
        <h4>🔐 <strong>Secure remote access.</strong></h4>
    </div>

    <div class="ribbon-content">
        <p>Battle-tested <a href="https://www.wireguard.com/">WireGuard</a> VPN tunnel. <strong>Easy setup and
                white-glove support.</strong>
        </p>
        <p>Seamless connection between mobile, home, workspace, and warehouse.</p>
    </div>

    <div class="ribbon ribbon-primary float-left">
        <h4>📡 Site to site networking.</h4>
    </div>

    <div class="ribbon-content">
        <p><strong>Link multiple printer farms.</strong></p>
        <p>Real-time monitoring across all work sites.</p>
        <p><strong>Sync files</strong> across all of your devices.</p>
        <img class="img-fluid" src="{% static 'images/print-nanny-file-manager.png'%}" />

    </div>
    </p>
</div>

print_nanny_webapp/templates/surveys/remote-access-thanks.html
{% extends "vertical_base.html" %}
{% load static %}
{% load crispy_forms_tags feature_flags %}

{% block content %}
<div class="account-pages mt-2 mb-5">
    <div class="container-fluid">
        <div class="card">
            <div class="card-body">

                <div class="card-header primary-gradient pt-4 pb-4 mb-4 text-center bg-primary text-white">
                    <h1>PrintNanny Network</h1>
                    <h3>Manage your 3D printers from anywhere in the world
                    </h3>

                    {% if not user.is_paid_beta_tester %}
                    <a target="_blank" href="{% url 'subscriptions:checkout' %}"
                        class="mt-2 mb-2 btn btn-lg btn-danger pull-left">Become a Founding Member</a>
                    <h3>{{ AVAILABLE_SUBSCRIPTIONS_COUNT }} spots left</h3>
                    {% endif %}

                </div>
                <div class="row">
                    <div class="col-12 ribbon-box col-md-6">
                        <div class="ribbon ribbon-primary float-left">
                            <h4 class="mb-2">PrintNanny OS + Network <span class="badge badge-light">Early Access</span>
                            </h4>
                        </div>
                        <div class="ribbon-content">
                            <h2 class="mb-4">Thank you for your interest!</h2>

                            {% if user.is_paid_beta_tester %}
                            <a target="_blank" href="{% url 'subscriptions:checkout' %}"
                                class="mt-2 mb-2 btn btn-lg btn-light pull-left">Become a Founding Member</a>
                            <h3>Founding Members like you help me make PrintNanny truly excellent! 💜</h3>
                            {% else %}
                            <h3>Your input helps me make PrintNanny truly excellent! 💜</h3>
                            {% endif %}

                            <p>I'll reach out over email if you're a fit PrintNanny's Network feature. </p>

                            {% if not user.is_paid_beta_tester %}
                            <h3 class="mt-4">Looking for immediate access to PrintNanny?</h3>
                            <h3>{{ AVAILABLE_SUBSCRIPTIONS_COUNT }} spots left</h3>
                            <p>Founding Members get <strong>early access to PrintNanny at a discount</strong> plus
                                exclusive swag.</p>
                            <p>I open a <strong>limited number of spots</strong> (typically 10) each month, so I can
                                provide <strong>white glove support</strong>.</p>
                            <p>Click <a href="{% url 'subscriptions:checkout' %}">Become a Founding Member</a> to learn
                                more.</p>
                            <a target="_blank" href="{% url 'subscriptions:checkout' %}"
                                class="mt-2 mb-2 btn btn-lg btn-danger">Become a Founding Member to Get Early Access</a>

                            {% endif %}
                        </div>
                    </div>
                    {% include 'surveys/remote-access-sidebar.html'%}
                </div>
            </div>

        </div>
    </div>
</div>
{% endblock content %}